/**
 * Configuration Bridge
 *
 * Imports buyer-customizable settings from config/ and exports a unified config object.
 * All components and lib files should import from here, not directly from config/.
 *
 * DO NOT EDIT this file — it is updated by the template maintainer.
 * To customize settings, edit the files in the config/ directory.
 */

import branding from '../../config/branding'
import prompts from '../../config/prompts'
import features from '../../config/features'
import integrations from '../../config/integrations'

export const config = {
  branding,
  prompts,
  features,
  integrations,
} as const

export type Config = typeof config
export type Branding = typeof branding
export type Prompts = typeof prompts
export type Features = typeof features
export type Integrations = typeof integrations

export { branding, prompts, features, integrations }
