#!/usr/bin/env npx tsx
/**
 * Interactive Setup Wizard
 *
 * Run with: npm run setup
 * Walks you through configuring your chatbot step by step.
 */

import * as readline from 'readline'
import * as fs from 'fs'
import * as path from 'path'
import { execSync } from 'child_process'

const rl = readline.createInterface({ input: process.stdin, output: process.stdout })

function ask(question: string): Promise<string> {
  return new Promise(resolve => rl.question(question, answer => resolve(answer.trim())))
}

function print(msg: string) { console.log(msg) }
function success(msg: string) { console.log(`  ✓ ${msg}`) }
function warn(msg: string) { console.log(`  ⚠ ${msg}`) }
function info(msg: string) { console.log(`  → ${msg}`) }

async function main() {
  print('')
  print('╔══════════════════════════════════════════════════════╗')
  print('║          AI Chatbot — Setup Wizard                  ║')
  print('╚══════════════════════════════════════════════════════╝')
  print('')
  print('This wizard will help you configure your chatbot.')
  print('You\'ll need:')
  print('  1. A Supabase account (https://supabase.com)')
  print('  2. An n8n account   (https://n8n.io)')
  print('  3. (Optional) A VAPI account for voice chat (https://vapi.ai)')
  print('')

  // ── Step 1: Company name ──────────────────────────────────────────────
  print('─── Step 1: Your Business ───')
  const businessName = await ask('What is your business name? ')

  if (businessName) {
    const brandingPath = path.join(__dirname, '..', 'config', 'branding.ts')
    if (fs.existsSync(brandingPath)) {
      let content = fs.readFileSync(brandingPath, 'utf-8')
      content = content.replace("businessName: 'My Business'", `businessName: '${businessName.replace(/'/g, "\\'")}'`)
      content = content.replace("chatTitle: 'AI Assistant'", `chatTitle: '${businessName.replace(/'/g, "\\'")} Assistant'`)
      fs.writeFileSync(brandingPath, content)
      success(`Updated config/branding.ts with "${businessName}"`)
    }

    const promptsPath = path.join(__dirname, '..', 'config', 'prompts.ts')
    if (fs.existsSync(promptsPath)) {
      let content = fs.readFileSync(promptsPath, 'utf-8')
      content = content.replace(/\{\{businessName\}\}/g, businessName)
      fs.writeFileSync(promptsPath, content)
      success('Updated config/prompts.ts with your business name')
    }
  }
  print('')

  // ── Step 2: Supabase ──────────────────────────────────────────────────
  print('─── Step 2: Supabase ───')
  info('Find these at: supabase.com → Your Project → Settings → API')
  print('')

  const supabaseUrl = await ask('Paste your Supabase Project URL: ')
  const supabaseAnonKey = await ask('Paste your Supabase anon (public) key: ')
  const supabaseServiceKey = await ask('Paste your Supabase service_role key (for chat history): ')
  print('')

  // ── Step 3: n8n ───────────────────────────────────────────────────────
  print('─── Step 3: n8n Webhook ───')
  info('This is the URL from your n8n Chat workflow\'s Webhook trigger node.')
  info('If you haven\'t created one yet, import n8n-workflows/simple-chat.json into n8n first.')
  print('')

  const n8nWebhookUrl = await ask('Paste your n8n webhook URL: ')
  print('')

  // ── Step 4: VAPI (optional) ───────────────────────────────────────────
  print('─── Step 4: Voice Chat (Optional) ───')
  const wantVoice = await ask('Do you want voice chat? (y/n) ')
  let vapiPublicKey = ''
  let vapiAssistantId = ''

  if (wantVoice.toLowerCase() === 'y') {
    info('Get these from: vapi.ai → Dashboard')
    vapiPublicKey = await ask('Paste your VAPI Public Key: ')
    vapiAssistantId = await ask('Paste your VAPI Assistant ID: ')
  } else {
    info('Skipping voice chat. You can enable it later by adding VAPI keys to .env.local')
  }
  print('')

  // ── Write .env.local ──────────────────────────────────────────────────
  print('─── Writing .env.local ───')
  const envContent = `# Generated by setup wizard
# Re-run: npm run setup

# Supabase
NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnonKey}
SUPABASE_SERVICE_ROLE_KEY=${supabaseServiceKey}

# n8n
N8N_WEBHOOK_URL=${n8nWebhookUrl}

# VAPI (voice chat)
NEXT_PUBLIC_VAPI_PUBLIC_KEY=${vapiPublicKey}
NEXT_PUBLIC_VAPI_ASSISTANT_ID=${vapiAssistantId}
`
  const envPath = path.join(__dirname, '..', '.env.local')
  fs.writeFileSync(envPath, envContent)
  success('Created .env.local')
  print('')

  // ── Install dependencies ──────────────────────────────────────────────
  const nodeModulesPath = path.join(__dirname, '..', 'node_modules')
  if (!fs.existsSync(nodeModulesPath)) {
    print('─── Installing dependencies ───')
    info('Running npm install (this may take a minute)...')
    try {
      execSync('npm install', { cwd: path.join(__dirname, '..'), stdio: 'inherit' })
      success('Dependencies installed')
    } catch {
      warn('npm install failed. Run it manually: npm install')
    }
    print('')
  }

  // ── Database setup guidance ───────────────────────────────────────────
  print('─── Database Setup ───')
  info('You need to run two SQL files in your Supabase SQL Editor:')
  info('  1. database/schema.sql  (creates tables)')
  info('  2. database/seed.sql    (adds default prompts)')
  print('')
  info('Steps:')
  info('  1. Go to supabase.com → Your Project → SQL Editor')
  info('  2. Click "New query"')
  info('  3. Copy the contents of database/schema.sql and click "Run"')
  info('  4. Do the same for database/seed.sql')
  print('')

  // ── Summary ───────────────────────────────────────────────────────────
  print('╔══════════════════════════════════════════════════════╗')
  print('║                  Setup Complete!                     ║')
  print('╚══════════════════════════════════════════════════════╝')
  print('')
  success('.env.local created')
  success(`Business name: ${businessName || '(not set)'}`)
  success(`Supabase: ${supabaseUrl ? 'configured' : 'missing'}`)
  success(`n8n webhook: ${n8nWebhookUrl ? 'configured' : 'missing'}`)
  success(`Voice chat: ${vapiPublicKey ? 'configured' : 'skipped'}`)
  print('')
  print('Next steps:')
  print('  1. Run the database SQL files (see above)')
  print('  2. Run: npm run doctor     (verify everything works)')
  print('  3. Run: npm run dev        (start your chatbot!)')
  print('')

  rl.close()
}

main().catch(err => {
  console.error('Setup failed:', err)
  rl.close()
  process.exit(1)
})
